version: '3'
services:
  app:
    build: .
    command: ./cmds.sh
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata: